time_zone: Asia/Kolkata
time_format: 02 Jan, 2006 - Mon @ 15:04

git_executable: /usr/bin/git
go_executable: /usr/bin/go
ffmpeg_executable: /usr/bin/ffmpeg
debug_mode: false

use_github_binaries: false
architecture:

telegram:
  bot_token: 186779
  #api_url: http://localhost:8082
  self_hosted_api: false
  owner_id: 704338780
  sudo_users_id:
    - 704338780
  target_chat_id: -100423424
  skip_video_stickers: false
  skip_setting_commands: false
  send_my_presence: false
  send_my_read_receipts: false
  silent_confirmation: true
  confirmation_type: "emoji"
  skip_startup_message: false
  spoiler_as_viewonce: true
  reactions: true

whatsapp:
  session_name: watgbridge
  tag_all_allowed_groups:
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 12xxxxxxxxxxxxx669
  ignore_chats:
    - 91xxxxxxxxxx
    - 12xxxxxxxxxxxxx669
  status_ignored_chats:
    - 91xxxxxxxxxx
    - 1xxxxxxxxxx
  skip_documents: false
  skip_images: false
  skip_gifs: false
  skip_videos: false
  skip_voice_notes: false
  skip_audios: false
  skip_stickers: false
  skip_status: false
  skip_contacts: false
  skip_locations: false
  skip_profile_picture_updates: false
  skip_group_settings_updates: false
  skip_chat_details: true
  send_revoked_message_updates: false
  whatsmeow_debug_mode: false
  send_my_messages_from_other_devices: false
  create_thread_for_info_updates: false
  sticker_metadata:
    pack_name: WaTgBridge
    author_name: WaTgBridge
  # New fields for pair code login
  use_pair_code: true
  phone_number: "+1234567890"

# Uncomment and configure one database section as needed

#database:
#  type: postgres
#  host: localhost
#  user: admin
#  password: password
#  dbname: gobot
#  port: 5432
#  time_zone: Asia/Kolkata

#database:
#  type: sqlite
#  path: ./gobot.sqlite.db

#database:
#  type: mysql
#  host: localhost
#  port: 3306
#  user: admin
#  password: password
#  dbname: gobot
